import 'dart:async';
import 'dart:math' show Random;

import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/widgets.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// App-wide sound effects and music with persisted toggles.
///
/// Files live in assets/audio/. All SFX are short WAVs generated by
/// tools/gen_cq_audio2.py. Repeatable effects ship as three round-robin
/// takes. Music plays only inside a game (see [claimMusic]): Coin Quest has
/// [trackQuest], When Pigs Fly [trackPigs], the cabinet games [trackLevel].
class Audio extends ChangeNotifier with WidgetsBindingObserver {
  static final Audio instance = Audio._();
  Audio._();

  bool _sfx = true;
  bool _music = true;
  bool _ready = false;
  bool _musicPlaying = false;
  SharedPreferences? _prefs;

  bool get sfx => _sfx;
  bool get music => _music;

  static const _sfxFiles = [
    'tap_1.wav', 'tap_2.wav', 'tap_3.wav',
    'swap_1.wav', 'swap_2.wav', 'swap_3.wav',
    'invalid_1.wav', 'invalid_2.wav', 'invalid_3.wav',
    'land_1.wav', 'land_2.wav', 'land_3.wav',
    'seal_1.wav', 'seal_2.wav', 'seal_3.wav',
    'coin_flip_1.wav', 'coin_flip_2.wav', 'coin_flip_3.wav',
    'pop1_1.wav', 'pop1_2.wav', 'pop1_3.wav',
    'pop2_1.wav', 'pop2_2.wav', 'pop2_3.wav',
    'pop3_1.wav', 'pop3_2.wav', 'pop3_3.wav',
    'pop4_1.wav', 'pop4_2.wav', 'pop4_3.wav',
    'pop5_1.wav', 'pop5_2.wav', 'pop5_3.wav',
    'special_create.wav', 'special_fire.wav', 'bomb.wav',
    'combo2.wav', 'combo3.wav', 'combo4.wav', 'combo5.wav',
    'win.wav', 'lose.wav', 'star1.wav', 'star2.wav', 'star3.wav',
    'vault_hit.wav', 'vault_break.wav', 'ingot_land.wav',
    'coin_roll.wav', 'coin_drop.wav', 'coin_spin.wav', 'ting.wav', 'coins_pour.wav',
    'vo_you_rock.wav', 'vo_wow.wav', 'vo_great_work.wav', 'vo_way_to_go.wav',
    'vo_keep_going.wav', 'vo_so_big.wav', 'vo_fire.wav', 'vo_unstoppable.wav',
    'vo_incredible.wav', 'vo_level_complete.wav', 'vo_you_win.wav',
    'vo_almost.wav', 'vo_one_more.wav', 'vo_got_this.wav',
    'vo_dont_give_up.wav', 'vo_believe.wav',
    'win_fill.wav',
    'fw_lift_1.wav', 'fw_lift_2.wav', 'fw_lift_3.wav',
    'fw_burst_1.wav', 'fw_burst_2.wav', 'fw_burst_3.wav',
    'fw_crackle_1.wav', 'fw_crackle_2.wav', 'fw_crackle_3.wav',
    'fw_finale.wav',
    // When Pigs Fly: the boar's wings and voice (tools/gen_pigs_sfx.py).
    'flap_piglet_1.wav', 'flap_piglet_2.wav', 'flap_piglet_3.wav',
    'grunt_piglet_1.wav', 'grunt_piglet_2.wav', 'grunt_piglet_3.wav', 'snort_piglet.wav',
    'flap_juvenile_1.wav', 'flap_juvenile_2.wav', 'flap_juvenile_3.wav',
    'grunt_juvenile_1.wav', 'grunt_juvenile_2.wav', 'grunt_juvenile_3.wav', 'snort_juvenile.wav',
    'flap_razorback_1.wav', 'flap_razorback_2.wav', 'flap_razorback_3.wav',
    'grunt_razorback_1.wav', 'grunt_razorback_2.wav', 'grunt_razorback_3.wav', 'snort_razorback.wav',
    'stage_up.wav',
    'ab_dash.wav', 'ab_grapple.wav', 'ab_blink.wav',
    'ab_freeze_fire.wav', 'ab_freeze_hit.wav', 'ab_tractor.wav',
  ];

  static const _coreFiles = [
    'tap_1.wav', 'swap_1.wav', 'invalid_1.wav', 'ting.wav',
    'coins_pour.wav', 'coin_flip_1.wav', 'win.wav',
  ];
  Future<void> init() async {
    if (_ready) return;
    _prefs = await SharedPreferences.getInstance();
    _sfx = _prefs!.getBool('audio.sfx') ?? true;
    _music = _prefs!.getBool('audio.music') ?? true;
    WidgetsBinding.instance.addObserver(this);
    try {
      FlameAudio.bgm.initialize();
      // The bed mixes rather than taking focus, same as the effects. Otherwise
      // every track change asks for and abandons audio focus, which is both
      // rude to whatever else is playing and visible as a stutter.
      await FlameAudio.bgm.audioPlayer.setAudioContext(_sfxContext);
    } catch (e) {
      debugPrint('audio init: $e');
    }
    _ready = true;
    notifyListeners();
    if (_music) startMusic();
    // Warm the players off the critical path. Web: only the handful every
    // screen shares, so first paint isn't waiting on 50 network fetches.
    // Native: assets are local, so build the lot.
    unawaited(_warm(kIsWeb ? _coreFiles : _sfxFiles));
  }

  // ---------------------------------------------------------------- sfx
  //
  // One persistent player per sound file, built on first use and kept for the
  // life of the app.
  //
  // The obvious call — FlameAudio.play(name) — is a trap on Android. Every
  // call constructs a fresh AudioPlayer, registers it with the plugin, and
  // appends it to the SoundPool's per-URL player list. Nothing ever takes it
  // back down: low-latency playback has no completion callback, so the
  // ReleaseMode.release that was supposed to clean up never fires. A few
  // minutes of cascades leaves hundreds of live players behind, each one more
  // work on every subsequent sample load, until effects drag and then go
  // silent for good. That was the "audio lags then stops" bug.
  //
  // Holding one player per file instead bounds the count at _sfxFiles.length,
  // loads each sample into the SoundPool exactly once, and reduces a replay to
  // two cheap platform calls.

  /// Memoised per-file players. Futures, not players, so two calls racing on
  /// the same sound can't build two of them.
  final Map<String, Future<AudioPlayer?>> _players = {};

  /// Effects mix with whatever else the device is playing. A 200 ms coin pop
  /// has no business grabbing audio focus, and asking for it per effect is
  /// what filled logcat with focus churn.
  static final AudioContext _sfxContext =
      AudioContextConfig(focus: AudioContextConfigFocus.mixWithOthers).build();

  Future<AudioPlayer?> _playerFor(String name) =>
      _players.putIfAbsent(name, () => _createPlayer(name));

  Future<AudioPlayer?> _createPlayer(String name) async {
    try {
      final p = AudioPlayer()..audioCache = FlameAudio.audioCache;
      await p.setPlayerMode(PlayerMode.lowLatency);
      await p.setAudioContext(_sfxContext);
      // stop, not release: release would unload the sample from the SoundPool
      // and we would pay the load cost again on the next hit.
      await p.setReleaseMode(ReleaseMode.stop);
      await p.setSource(AssetSource(name));
      return p;
    } catch (e) {
      debugPrint('sfx load $name: $e');
      return null;
    }
  }

  /// Builds every player once, in sequence, so the first hit of each sound is
  /// as prompt as the rest. Sequential on purpose — firing 50 source loads at
  /// the platform channel at once is its own stall.
  Future<void> _warm(List<String> files) async {
    for (final f in files) {
      await _playerFor(f);
    }
  }

  /// Round-robin cursor per sound family, so a long cascade doesn't fire the
  /// identical sample twelve times.
  final Map<String, int> _rrCursor = {};

  /// When each family last played, for the limiter below.
  final Map<String, int> _lastPlayed = {};

  /// Rolling window of recent voice starts.
  final List<int> _recentVoices = [];

  /// The SoundPool carries 32 streams. This ceiling is about taste, not
  /// capacity — it keeps a deep cascade percussive instead of muddy.
  static const _maxVoicesPerHalfSecond = 12;

  // ------------------------------------------------------- instrumentation
  //
  // The original bug was effects lagging and then stopping outright, which is
  // a failure nobody notices until it has already happened. These counters
  // make it measurable: a leak of the old kind shows as latency climbing run
  // over run long before anything goes silent, so the last-decile latency
  // against the first is the number that matters, not the totals.
  //
  // Reading them costs nothing when unused; the soak screen in the DEV build
  // is the only consumer.

  int sfxAttempts = 0, sfxPlayed = 0, sfxFailed = 0, sfxLimited = 0;

  /// Milliseconds from asking for a sound to the platform accepting it.
  /// Capped so a long session cannot grow this without bound.
  final List<int> sfxLatencies = [];
  static const _maxLatencySamples = 20000;

  void resetStats() {
    sfxAttempts = sfxPlayed = sfxFailed = sfxLimited = 0;
    sfxLatencies.clear();
  }

  void play(String name, {double volume = 1.0, int minGapMs = 0}) {
    if (!_sfx || !_ready) return;
    final now = DateTime.now().millisecondsSinceEpoch;
    // Per-sound spacing: a rapid repeat of the same sample is what turns a
    // cascade into mush, so drop it rather than stack it.
    if (minGapMs > 0 && now - (_lastPlayed[name] ?? 0) < minGapMs) {
      sfxLimited++;
      return;
    }
    // Global voice ceiling over a short window.
    _recentVoices.removeWhere((ts) => now - ts > 500);
    if (_recentVoices.length >= _maxVoicesPerHalfSecond) {
      sfxLimited++;
      return;
    }
    _lastPlayed[name] = now;
    _recentVoices.add(now);
    sfxAttempts++;
    unawaited(_fire(name, volume));
  }

  Future<void> _fire(String name, double volume) async {
    final sw = Stopwatch()..start();
    try {
      final p = await _playerFor(name);
      if (p == null || !_sfx) return;
      // Volume is read when the stream starts, so it has to be set first.
      await p.setVolume(volume);
      // stop() clears the SoundPool stream id, which is what makes the
      // following call start the sample from the top rather than try to resume
      // a stream that already finished.
      await p.stop();
      await p.resume();
      sfxPlayed++;
      if (sfxLatencies.length < _maxLatencySamples) {
        sfxLatencies.add(sw.elapsedMilliseconds);
      }
    } catch (e) {
      sfxFailed++;
      debugPrint('sfx $name: $e');
    }
  }

  /// Every effect the soak can draw from.
  List<String> get allSfx => List.unmodifiable(_sfxFiles);

  /// Plays the next take of a round-robin family, e.g. `pop3_` -> pop3_2.wav.
  void _rr(String family, int takes, {double volume = 1.0, int minGapMs = 0}) {
    final i = ((_rrCursor[family] ?? 0) % takes) + 1;
    _rrCursor[family] = i;
    play('$family$i.wav', volume: volume, minGapMs: minGapMs);
  }

  void tap() => _rr('tap_', 3, volume: 0.6, minGapMs: 40);
  void swap() => _rr('swap_', 3, volume: 0.7, minGapMs: 40);
  void invalid() => _rr('invalid_', 3, volume: 0.8, minGapMs: 80);

  /// Pop pitch and tail both rise with cascade depth (1..5).
  void pop(int depth) => _rr('pop${depth.clamp(1, 5)}_', 3, volume: 0.8, minGapMs: 45);
  void land() => _rr('land_', 3, volume: 0.5, minGapMs: 60);
  void specialCreate() => play('special_create.wav', volume: 0.8, minGapMs: 90);
  void specialFire() => play('special_fire.wav', volume: 0.9, minGapMs: 90);
  void bomb() => play('bomb.wav', minGapMs: 120);
  void combo(int n) => play('combo${n.clamp(2, 5)}.wav', volume: 0.8, minGapMs: 100);
  void win() => play('win.wav');
  void lose() => play('lose.wav', volume: 0.9);
  void star(int n) => play('star${n.clamp(1, 3)}.wav', volume: 0.9);
  // `payout()` and its sample are gone: nothing called it, and shipping a file
  // literally named "payout" in an app that must not imply monetary reward is
  // an avoidable thing to find in an APK teardown.
  void coinFlip() => _rr('coin_flip_', 3, volume: 0.7, minGapMs: 40);
  void coinRoll() => play('coin_roll.wav', volume: 0.7, minGapMs: 50);
  void coinDrop() => play('coin_drop.wav', volume: 0.6, minGapMs: 60);
  void coinSpin() => play('coin_spin.wav', volume: 0.5, minGapMs: 80);
  void ting() => play('ting.wav', volume: 0.35, minGapMs: 70);
  void coinsPour() => play('coins_pour.wav', volume: 0.7, minGapMs: 200);

  // Objective sounds.
  void sealStrip() => _rr('seal_', 3, volume: 0.55, minGapMs: 55);
  void vaultHit() => play('vault_hit.wav', volume: 0.8, minGapMs: 90);
  void vaultBreak() => play('vault_break.wav', volume: 0.95, minGapMs: 110);
  void ingotLand() => play('ingot_land.wav', minGapMs: 150);

  // ------------------------------------------------------------ voice

  /// True inside the DGD App tab (--dart-define=DGD_APP_TAB=true).
  ///
  /// The arcade plan bars prize-style celebration in-App, so the winner line
  /// and the fireworks are standalone-only. Everything else is identical.
  static const inAppTab = bool.fromEnvironment('DGD_APP_TAB');

  /// Cascade affirmations, in two tiers.
  ///
  /// A four-chain and a nine-chain are not the same event, and praising them
  /// identically flattens both. The big lines are held back for 6+ so they
  /// keep meaning something when they land.
  static const _praise = [
    'vo_you_rock.wav',
    'vo_wow.wav',
    'vo_great_work.wav',
    'vo_way_to_go.wav',
    'vo_keep_going.wav',
  ];
  static const _praiseBig = [
    'vo_so_big.wav',
    'vo_fire.wav',
    'vo_unstoppable.wav',
    'vo_incredible.wav',
  ];
  static const _winLines = ['vo_level_complete.wav', 'vo_you_win.wav'];

  /// Spoken when the moves run out.
  ///
  /// Ordered softest-first and rotated, not random: the first loss on a level
  /// gets "Almost had it", and only a player who keeps failing the same level
  /// hears "I believe in you". Random order would open with the big
  /// reassurance on a near-miss, which reads as pity rather than encouragement.
  static const _loseLines = [
    'vo_almost.wav',
    'vo_one_more.wav',
    'vo_got_this.wav',
    'vo_dont_give_up.wav',
    'vo_believe.wav',
  ];

  /// Start somewhere random, or every session opens on the same line and the
  /// rotation is only audible to people who play twice.
  int _praiseCursor = Random().nextInt(_praise.length);
  int _bigCursor = Random().nextInt(_praiseBig.length);
  int _winCursor = Random().nextInt(_winLines.length);

  /// Not random, unlike the others — see [_loseLines]. The softest line first.
  int _loseCursor = 0;
  int _lastPraise = 0;

  /// Cascade depth that earns a spoken affirmation, and the depth that earns
  /// the bigger one. The two call sites in `match3_game.dart` both read these
  /// rather than repeating the number — they used to hold `4` and `6`
  /// literally, kept in step by a comment.
  ///
  /// Loosened 2026-09-21, from 4/6 and a 7 s gap. The win line is suppressed
  /// inside the DGD app (§4.3, see [voWinner]), and that is the line a player
  /// would otherwise hear most — so the embed was close to silent on early
  /// levels, where small boards rarely chain four deep.
  ///
  /// These are the tuning knobs. Raise them if praise starts to feel like a
  /// tic; that failure mode is the reason the rate limit exists at all.
  static const praiseCombo = 3;
  static const praiseBigCombo = 5;

  /// Minimum gap between spoken affirmations.
  static const praiseGapMs = 4500;

  /// Spoken on a deep cascade. Rate-limited: an affirmation that fires on
  /// every chain stops being one.
  ///
  /// The gap is held across both tiers rather than per line — two different
  /// affirmations back to back is still two affirmations back to back, which
  /// is the repetition the rotation exists to avoid.
  void voPraise({bool big = false}) {
    if (!_sfx || !_ready) return;
    final now = DateTime.now().millisecondsSinceEpoch;
    if (now - _lastPraise < praiseGapMs) return;
    _lastPraise = now;
    play(
      big
          ? _praiseBig[_bigCursor++ % _praiseBig.length]
          : _praise[_praiseCursor++ % _praise.length],
      volume: 0.95,
    );
  }

  /// Spoken on level completion, standalone builds only.
  void voWinner() {
    if (inAppTab) return;
    play(_winLines[_winCursor++ % _winLines.length], volume: 0.95, minGapMs: 3000);
  }

  /// Spoken when a level is lost.
  ///
  /// Unlike the winner line this is not gated on [inAppTab]: encouragement
  /// after a failure is not prize-style celebration, so the arcade plan's
  /// §4.3 restriction does not reach it.
  void voEncourage() =>
      play(_loseLines[_loseCursor++ % _loseLines.length], volume: 0.95, minGapMs: 3000);

  void winFill() => play('win_fill.wav', volume: 0.55);

  // -------------------------------------------------------- fireworks
  //
  // Three sounds per shell, not one. A single "boom" is what makes game
  // fireworks read as a door slamming: the lift tells you something is coming,
  // the break gives it a position, and the crackle is what a firework actually
  // sounds like a second later. Built by tools/gen_fireworks.py.

  void fwLift() => _rr('fw_lift_', 3, volume: 0.30, minGapMs: 90);
  void fwBurst() => _rr('fw_burst_', 3, volume: 0.80, minGapMs: 70);
  void fwCrackle() => _rr('fw_crackle_', 3, volume: 0.38, minGapMs: 120);
  void fwFinale() => play('fw_finale.wav', volume: 0.85, minGapMs: 1500);

  // When Pigs Fly. [stage] is the boar's stage id: piglet, juvenile or
  // razorback. Its wings and voice change as it grows.

  /// A wingbeat, on every flap. Quiet and quick: players flap a lot.
  void pigFlap(String stage) => _rr('flap_${stage}_', 3, volume: 0.42, minGapMs: 70);

  /// The boar's cry on striking a gate, over the impact.
  void pigGrunt(String stage) => _rr('grunt_${stage}_', 3, volume: 0.75, minGapMs: 300);

  /// A contented snort on touchdown.
  void pigSnort(String stage) => play('snort_$stage.wav', volume: 0.7, minGapMs: 500);

  /// The boar has grown into its next stage.
  void stageUp() => play('stage_up.wav', volume: 0.85, minGapMs: 2000);

  // When Pigs Fly's abilities, one sound each (tools/gen_pigs_sfx.py). They
  // sound like gear, not like the boar: they are what the shop sells.
  void abDash() => play('ab_dash.wav', volume: 0.8, minGapMs: 200);
  void abGrapple() => play('ab_grapple.wav', volume: 0.8, minGapMs: 200);
  void abBlink() => play('ab_blink.wav', volume: 0.8, minGapMs: 200);
  void abFreezeFire() => play('ab_freeze_fire.wav', volume: 0.7, minGapMs: 200);

  /// The freeze shot reaching its coin.
  void abFreezeHit() => play('ab_freeze_hit.wav', volume: 0.75, minGapMs: 200);
  void abTractor() => play('ab_tractor.wav', volume: 0.75, minGapMs: 500);

  // ---------------------------------------------------------------- music

  /// Music plays only inside a game, never in the arcade's menus (the owner's
  /// call, 2026-09-29). A screen that belongs to a game claims its track with
  /// [claimMusic] and gives it back with [releaseMusic]; with no claim
  /// outstanding the arcade is silent.
  ///
  /// Coin Quest: "Quest Tune", the owner's own track (2026-09-29), one tune
  /// from the level map through every level. Encoded mono at 96 kbps and
  /// brought from -12.5 to about -20 LUFS, where the other beds sit, since
  /// all music plays at one volume; a 20 ms fade in and a 1.5 s fade out
  /// soften the loop.
  static const trackQuest = 'music_quest.mp3';

  /// The cabinet games' bed.
  static const trackLevel = 'music_level.mp3';

  /// When Pigs Fly: "Flight of the Swine", the owner's own track
  /// (2026-09-27). Encoded from the 48 kHz WAV at 128 kbps and brought down
  /// from -8.5 to about -20 LUFS, where the other beds sit, since all music
  /// plays at one volume; a 20 ms fade in and a 1.5 s fade out soften the
  /// loop, which the source does not fade into. It is not in the others'
  /// key, so switching to or from it is a change of song, not a crossfade.
  static const trackPigs = 'music_pigs.mp3';

  static const _musicVolume = 0.28;

  /// The bed that has been asked for; null is silence.
  String? _track;

  /// The bed actually on the player. These drift apart while a fade runs.
  String? _playingTrack;

  String? get track => _track;
  bool _switching = false;

  final List<(int, String)> _claims = [];
  int _lastClaim = 0;

  /// Plays [track] while the claiming screen is up. Call [releaseMusic] with
  /// the result from that screen's dispose.
  int claimMusic(String track) {
    final id = ++_lastClaim;
    _claims.add((id, track));
    setTrack(track);
    return id;
  }

  /// Gives a claim back: the screen underneath's music resumes, or, with
  /// nothing left, the music fades out. Claims are released by id, not in
  /// order, so a pushReplacement (new screen claims before the old one
  /// releases) carries on without a gap.
  void releaseMusic(int id) {
    _claims.removeWhere((c) => c.$1 == id);
    setTrack(_claims.isEmpty ? null : _claims.last.$2);
  }

  Future<void> startMusic() async {
    final t = _track;
    if (!_music || !_ready || _musicPlaying || t == null) return;
    _musicPlaying = true;
    try {
      await FlameAudio.bgm.play(t, volume: _musicVolume);
      _playingTrack = t;
    } catch (e) {
      debugPrint('bgm: $e');
      _musicPlaying = false;
    }
  }

  /// Crossfades to another bed, or with null fades out to silence. No-op if
  /// that is already what is playing.
  ///
  /// flame_audio drives a single background player, so this is a fade-out /
  /// swap / fade-in rather than a true overlap — short enough (≈250 ms each
  /// way) that it reads as a crossfade.
  Future<void> setTrack(String? next) async {
    if (_track == next && (_musicPlaying || next == null)) return;
    _track = next;
    if (!_music || !_ready) return;
    // A switch already in flight will pick up the new _track when it finishes,
    // rather than two fades fighting over one player.
    if (_switching) return;
    _switching = true;
    try {
      // Screens can change faster than a fade, so keep going until the bed
      // that is playing is the bed that was last asked for.
      while (_playingTrack != _track) {
        final want = _track;
        if (_musicPlaying) {
          for (var i = 5; i >= 0; i--) {
            await FlameAudio.bgm.audioPlayer.setVolume(_musicVolume * i / 5);
            await Future.delayed(const Duration(milliseconds: 45));
          }
          await FlameAudio.bgm.stop();
          _musicPlaying = false;
          _playingTrack = null;
        }
        if (want == null) continue; // silence: faded out and stopped
        await FlameAudio.bgm.play(want, volume: 0);
        _musicPlaying = true;
        _playingTrack = want;
        for (var i = 0; i <= 5; i++) {
          await FlameAudio.bgm.audioPlayer.setVolume(_musicVolume * i / 5);
          await Future.delayed(const Duration(milliseconds: 45));
        }
      }
    } catch (e) {
      debugPrint('bgm switch: $e');
    } finally {
      _switching = false;
    }
  }

  Future<void> stopMusic() async {
    _musicPlaying = false;
    _playingTrack = null;
    try {
      await FlameAudio.bgm.stop();
    } catch (_) {}
  }

  // ---------------------------------------------------------------- settings

  Future<void> setSfx(bool v) async {
    _sfx = v;
    await _prefs?.setBool('audio.sfx', v);
    notifyListeners();
  }

  Future<void> setMusic(bool v) async {
    _music = v;
    await _prefs?.setBool('audio.music', v);
    notifyListeners();
    if (v) {
      startMusic();
    } else {
      stopMusic();
    }
  }

  // Pause the bed when the app goes to background.
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (!_music) return;
    switch (state) {
      case AppLifecycleState.paused:
      case AppLifecycleState.inactive:
      case AppLifecycleState.hidden:
        FlameAudio.bgm.pause();
      case AppLifecycleState.resumed:
        // Only a bed that was playing comes back; a silent menu stays silent.
        if (_musicPlaying) FlameAudio.bgm.resume();
      case AppLifecycleState.detached:
        break;
    }
  }
}
