/// The flying piggy bank — When Pigs Fly's player, in three stages.
///
/// The boar grows across runs (phase 2 wires that to lifetime points on the
/// server); within a run the stage is fixed. What changes with the stage is
/// the art and how big it is drawn. What does **not** change is the hitbox:
/// the simulation still flies a circle of the coin's old radius, so the
/// razorback a player has spent weeks growing is never harder to fit through
/// a gap than the piglet they started with. The wings, crest and mane are
/// allowed to overlap a pillar harmlessly — they are decoration, not body.
///
/// ## The sheet contract
///
/// Each stage is one PNG: a single row of [BoarFrame.count] square frames,
/// facing right, the frame side being the image height. Final art replaces
/// these files without a code change as long as it keeps that layout and
/// roughly the placements in [BoarSpec] — or updates the three numbers there.
/// The placeholder sheets are generated by `tool/art/boar_sprites.py`.
library;

import 'package:flutter/widgets.dart';

enum BoarStage {
  piglet,
  juvenile,
  razorback;

  /// The server's stage id — the enum name — or null for anything unknown,
  /// so a stage added on the server before the app knows it falls back to
  /// the caller's default rather than throwing.
  static BoarStage? fromId(String? id) {
    for (final s in values) {
      if (s.name == id) return s;
    }
    return null;
  }

  String get label => BoarSpec.all[this]!.name;
}

/// Frame indices within every sheet.
abstract final class BoarFrame {
  /// Wing cycle: up, mid, down, recovery.
  static const cycle = [0, 1, 2, 3];
  static const hurt = 4;

  /// Swept-back wings. Reserved for the dash ability (phase 3).
  static const dash = 5;

  /// Wings braking, legs down: the last metres before touchdown.
  static const land = 6;

  /// Wings folded, standing on the ground.
  static const stand = 7;
  static const count = 8;
}

class BoarSpec {
  /// Bare file name under assets/images/, the way Flame loads it.
  final String file;

  /// Frame side on screen, in hitbox radii. Grows with the stage; the hitbox
  /// does not.
  final double sizeInRadii;

  /// Where the hitbox centre sits in the frame, as fractions of its side.
  /// Roughly the middle of body-and-head, not the middle of the frame — the
  /// frame has headroom for the wings.
  final double anchorU, anchorV;

  /// Where the hooves meet the ground in the standing frame, as a fraction of
  /// the frame height, so a landed boar stands on the ground line rather
  /// than hovering over it or sinking into it.
  final double footV;

  /// Shown on the pre-run and results screens once growth is live.
  final String name;

  /// The body's collision shape: a horizontal capsule centred on the anchor,
  /// in radii of the old coin. [bodyRadius] is its half-height and is the
  /// same at every stage, and smaller than the coin's, so no stage is harder
  /// to fit through a gap than the coin was. [bodyHalfLength] is the straight
  /// run between the two round ends, and grows with the body, so a snout or
  /// a rump that visibly meets a pillar counts. The first version kept the
  /// coin's circle, and on device the razorback's snout sank most of a
  /// radius into a pillar before a strike registered.
  final double bodyRadius, bodyHalfLength;

  const BoarSpec({
    required this.file,
    required this.sizeInRadii,
    required this.anchorU,
    required this.anchorV,
    required this.footV,
    required this.name,
    this.bodyRadius = 0.9,
    required this.bodyHalfLength,
  });

  static const all = {
    BoarStage.piglet: BoarSpec(
      file: 'boar_piglet.png',
      sizeInRadii: 5.6,
      anchorU: 0.484,
      anchorV: 0.553,
      footV: 0.79,
      name: 'Piglet',
      bodyHalfLength: 0.35,
    ),
    BoarStage.juvenile: BoarSpec(
      file: 'boar_juvenile.png',
      sizeInRadii: 6.6,
      anchorU: 0.491,
      anchorV: 0.567,
      footV: 0.79,
      name: 'Juvenile',
      bodyHalfLength: 0.5,
    ),
    BoarStage.razorback: BoarSpec(
      file: 'boar_razorback.png',
      sizeInRadii: 7.8,
      anchorU: 0.464,
      anchorV: 0.567,
      footV: 0.785,
      name: 'Razorback',
      bodyHalfLength: 0.62,
    ),
  };
}

/// One frame of a stage's sheet as a Flutter widget — the standing boar by
/// default — for the screens around the game. Unfiltered, like in flight.
class BoarPortrait extends StatelessWidget {
  final BoarStage stage;
  final double size;
  final int frame;
  const BoarPortrait({super.key, required this.stage, this.size = 56, this.frame = BoarFrame.stand});

  /// The part of a frame the boar actually occupies when standing, as
  /// fractions: frames carry headroom for raised wings, and drawn whole the
  /// standing boar filled barely half a 58 px portrait on device.
  static const _crop = Rect.fromLTWH(0.10, 0.18, 0.72, 0.72);

  @override
  Widget build(BuildContext context) {
    final f = size / _crop.width; // one frame's side at this zoom
    return SizedBox.square(
      dimension: size,
      child: ClipRect(
        child: OverflowBox(
          alignment: Alignment.topLeft,
          maxWidth: f * BoarFrame.count,
          maxHeight: f,
          child: Transform.translate(
            offset: Offset(-(frame + _crop.left) * f, -_crop.top * f),
            child: Image.asset(
              'assets/images/${BoarSpec.all[stage]!.file}',
              width: f * BoarFrame.count,
              height: f,
              fit: BoxFit.fill,
              filterQuality: FilterQuality.none,
              errorBuilder: (_, __, ___) => const SizedBox.shrink(),
            ),
          ),
        ),
      ),
    );
  }
}
