/// The flying piggy bank — When Pigs Fly's player, in three stages.
///
/// The boar grows across runs (phase 2 wires that to lifetime points on the
/// server); within a run the stage is fixed. What changes with the stage is
/// the art and how big it is drawn. What does **not** change is the hitbox:
/// the simulation still flies a circle of the coin's old radius, so the
/// razorback a player has spent weeks growing is never harder to fit through
/// a gap than the piglet they started with. The wings, crest and mane are
/// allowed to overlap a pillar harmlessly — they are decoration, not body.
///
/// ## The sheet contract
///
/// Each stage is one PNG: a single row of [BoarFrame.count] square frames,
/// facing right, the frame side being the image height. Final art replaces
/// these files without a code change as long as it keeps that layout and
/// roughly the placements in [BoarSpec] — or updates the three numbers there.
/// The placeholder sheets are generated by `tool/art/boar_sprites.py`.
library;

enum BoarStage { piglet, juvenile, razorback }

/// Frame indices within every sheet.
abstract final class BoarFrame {
  /// Wing cycle: up, mid, down, recovery.
  static const cycle = [0, 1, 2, 3];
  static const hurt = 4;

  /// Swept-back wings. Reserved for the dash ability (phase 3).
  static const dash = 5;

  /// Wings braking, legs down: the last metres before touchdown.
  static const land = 6;

  /// Wings folded, standing on the ground.
  static const stand = 7;
  static const count = 8;
}

class BoarSpec {
  /// Bare file name under assets/images/, the way Flame loads it.
  final String file;

  /// Frame side on screen, in hitbox radii. Grows with the stage; the hitbox
  /// does not.
  final double sizeInRadii;

  /// Where the hitbox centre sits in the frame, as fractions of its side.
  /// Roughly the middle of body-and-head, not the middle of the frame — the
  /// frame has headroom for the wings.
  final double anchorU, anchorV;

  /// Where the hooves meet the ground in the standing frame, as a fraction of
  /// the frame height, so a landed boar stands on the ground line rather
  /// than hovering over it or sinking into it.
  final double footV;

  /// Shown on the pre-run and results screens once growth is live.
  final String name;

  const BoarSpec({
    required this.file,
    required this.sizeInRadii,
    required this.anchorU,
    required this.anchorV,
    required this.footV,
    required this.name,
  });

  static const all = {
    BoarStage.piglet: BoarSpec(
      file: 'boar_piglet.png',
      sizeInRadii: 5.6,
      anchorU: 0.484,
      anchorV: 0.553,
      footV: 0.79,
      name: 'Piglet',
    ),
    BoarStage.juvenile: BoarSpec(
      file: 'boar_juvenile.png',
      sizeInRadii: 6.6,
      anchorU: 0.491,
      anchorV: 0.567,
      footV: 0.79,
      name: 'Juvenile',
    ),
    BoarStage.razorback: BoarSpec(
      file: 'boar_razorback.png',
      sizeInRadii: 7.8,
      anchorU: 0.464,
      anchorV: 0.567,
      footV: 0.785,
      name: 'Razorback',
    ),
  };
}
